### ISSUE TITLE
Remake Power Tracker Board

### ISSUE THREAD

**Issue by fabio-gustav** [Illinois-State-Solar-Car/array#1]
Redo the wiring for the power tracker boards to clean them up

**Comment by Austin8462** [comment]
Redesign work has begun. Dimensions were given to Mech and panel should be cut today. Once done, a mounting plan can begin to be finalized.

**Comment by Austin8462** [comment]
Physical power tracker (PT) board is made. High voltage shunts and power trackers have been mounted, secure mounting for the overall panel is in place. PT connectors have been remade with work on main umbilical for car --> wing being mostly complete. Wire mangement as well as additional wire runs are still oustanding.

**Comment by fabio-gustav** [comment]
PT board is wired, it needs some labeling on the wires and the mppts need to be changed to support the higher pack voltage

**Comment by fabio-gustav** [comment]
Need to put in the kill-switch bypass

**Comment by fabio-gustav** [comment]
Bypass done
